const en = {
  loading_msg: "Preparing for chicken..",
  button_language: 'Language',
  button_language_pleaseselect: 'Please select Language',
  button_language_close: 'Close',

  topNavBar_notconnected: "Not connected to any blockchain",
  topNavBar_connected: 'Connected to',

  shopManagementScreen_tabtitle_qrmenu: 'QR Menu',
  shopManagementScreen_tabtitle_receivedorder: 'Received Orders',

  offlineQRMenuListLayout_title: 'QR Menu Items',
  offlineQRMenuListLayout_itemlist_showQR: 'QR Code',
  offlineQRMenuListLayout_itemlist_testOrder: 'Test Order',
  offlineQRMenuListLayout_itemlist_delete: 'Delete',
  offlineQRMenuListLayout_itemEntry_itemName: 'Item\'s Name',
  offlineQRMenuListLayout_itemEntry_desc: 'Please enter item\'s description',
  offlineQRMenuListLayout_itemEntry_selectToken: 'Select Crypto',
  offlineQRMenuListLayout_itemEntry_price: 'Price',
  offlineQRMenuListLayout_itemEntry_savebutton_create: 'Create',
  offlineQRMenuListLayout_itemEntry_savebutton_update: 'Update',
  offlineItemEditCard_dateCreated: 'Date Created',
  offlineItemEditCard_dateUpdated: 'Last Updated',
  offlineQRMenuListLayout_askConfirmDelete: 'Confirm to delete?',
  offlineQRMenuListLayout_delete: 'DELETE',
  offlineQRMenuListLayout_item_crypto: 'Crypto',
  offlineQRMenuListLayout_item_price: 'Price',
  offlineQRMenuListLayout_item_desc: 'Description',
  offlineQRMenuListLayout_button_exportQR: 'Export QR Code',

  receivedQROrderListLayout_title_receivedOrders: 'Received Orders',
  receivedQROrderListLayout_title_archivedOrders: 'Archived Orders',
  receivedQROrderListLayout_askDelete_ReceivedOrder: 'Delete an order. You sure?',
  receivedQROrderListLayout_askDelete_ArchivedOrder: 'Delete an archived order. You sure?',
  receivedQROrderListLayout_deleteButton_Received: 'DELETE',
  receivedQROrderListLayout_deleteButton_Archived: 'DELETE',
  receivedQROrderListLayout_list_btn_delete: 'Delete',
  receivedQROrderListLayout_list_btn_refund: 'Refund',
  receivedQROrderListLayout_list_btn_save: 'Save',

  qROrderViewCard_orderId: 'Order ID',
  qROrderViewCard_receivedDate: 'Date/Time',
  qROrderViewCard_order_name: 'Name',
  qROrderViewCard_order_crypto: 'Crypto',
  qROrderViewCard_order_price: 'Price',
  qROrderViewCard_order_fromAddr: 'From',
  qROrderViewCard_order_blockChain: 'BlockChain',
  qROrderViewCard_button_txDetails: 'Transaction Details',
  qROrderViewCard_button_contractDetails: 'Crypto Contract Address',
  qROrderViewCard_button_delete: 'DELETE Order',
  qROrderViewCard_button_confirmdelete: 'CONFIRM DELETE',

};

export default en;
