const zhHK = {
  loading_msg: "載入中請稍候..",
  button_language: '語言',
  button_language_pleaseselect: '請選擇語言',
  button_language_close: '關閉',

  topNavBar_notconnected: '尚未連接加密錢包',
  topNavBar_connected: '已連接加密錢包至',

  shopManagementScreen_tabtitle_qrmenu: 'QR商品目錄',
  shopManagementScreen_tabtitle_receivedorder: '已接收訂單',

  offlineQRMenuListLayout_title: '目錄清單',
  offlineQRMenuListLayout_itemlist_showQR: 'QR二維碼',
  offlineQRMenuListLayout_itemlist_testorder: '測試訂單',
  offlineQRMenuListLayout_itemlist_delete: '刪除',
  offlineQRMenuListLayout_itemEntry_itemName: '請輸入商品名稱',
  offlineQRMenuListLayout_itemEntry_desc: '商品說明/描述',
  offlineQRMenuListLayout_itemEntry_selectToken: '請選擇加密貨幣',
  offlineQRMenuListLayout_itemEntry_price: '請輸入價格',
  offlineQRMenuListLayout_itemEntry_savebutton_create: '新增商品',
  offlineQRMenuListLayout_itemEntry_savebutton_update: '修改商品',
  offlineItemEditCard_dateCreated: '創建日期',
  offlineItemEditCard_dateUpdated: '更新日期',
  offlineQRMenuListLayout_askConfirmDelete: '確定刪除?',
  offlineQRMenuListLayout_askConfirmDelete2: '此動作無法復原',
  offlineQRMenuListLayout_delete: '刪除',
  offlineQRMenuListLayout_item_crypto: '加密貨幣',
  offlineQRMenuListLayout_item_price: '價格',
  offlineQRMenuListLayout_item_desc: '商品描述',
  offlineQRMenuListLayout_button_exportQR: '導出QR碼',
  offlineQRMenuListLayout_exportQR_saved: '已儲存至相簿',

  receivedQROrderListLayout_title_receivedOrders: '已接收訂單',
  receivedQROrderListLayout_title_archivedOrders: '已存檔訂單',
  receivedQROrderListLayout_askDelete_ReceivedOrder: '確定刪除訂單? 此動作無法復原',
  receivedQROrderListLayout_askDelete_ArchivedOrder: '確定刪除訂單存檔? 此動作無法復原',
  receivedQROrderListLayout_deleteButton_Received: '刪除訂單',
  receivedQROrderListLayout_deleteButton_Archived: '刪除存檔',
  receivedQROrderListLayout_list_btn_delete: '刪除',
  receivedQROrderListLayout_list_btn_refund: '退款',
  receivedQROrderListLayout_list_btn_save: '存檔',

  qROrderViewCard_orderId: '訂單編號',
  qROrderViewCard_receivedDate: '接收日期',
  qROrderViewCard_order_name: '商品名稱',
  qROrderViewCard_order_crypto: '使用貨幣',
  qROrderViewCard_order_price: '價格',
  qROrderViewCard_order_fromAddr: '付款錢包',
  qROrderViewCard_order_blockChain: '區塊鏈',
  qROrderViewCard_button_txDetails: '交易詳情 (Etherscan)',
  qROrderViewCard_button_contractDetails: '加密貨幣合約 (Etherscan)',
  qROrderViewCard_button_delete: '刪除訂單',
  qROrderViewCard_button_confirmdelete: '確定刪除',

  userSettingEditCard_name: '用戶暱稱',
  userSettingEditCard_deilveryAddress: '送貨地址',
  userSettingEditCard_savebutton: '儲存',
  userSettingEditCard_topMsg: '為提高用戶體驗，請輸入您的用戶暱稱及送貨地址',
  userSettingEditCard_topMsg2: '請輸入您的用戶暱稱及送貨地址',
  userSettingEditCard_topMsg3: '請注意，這些資料僅用於本地存儲',
  userSettingEditCard_topMsg4: '但我們不建議您使用真實姓名或地址',

  qrscanner_askConfirm: '請確定付款',
  qrscanner_askConfirm_itemName: '商品名稱',
  qrscanner_askConfirm_itemPrice: '價格',
  qrscanner_askConfirm_receiverAddr: '收款人錢包地址',
  qrscanner_askConfirm_btn_confirm: '確定',
  qrscanner_askConfirm_btn_cancel: '取消',

  qrscanner_confirming_msg1: '處理中..',
  qrscanner_confirming_msg2: '請留意Metamask確認信息',
  qrscanner_confirming_msg3: '畫面或會來回跳動數次，請安心等待',
  qrscanner_confirming_cancel: '取消交易',

  qrscanner_fail_msg1: '交易失敗',
  qrscanner_fail_msg2: '返回主頁',

  qrscanner_success_msg1: '交易成功',
  qrscanner_success_msg2: '繼續',


};

export default zhHK;